### PR TITLE
Return an empty data structure and not null.

### PR DESCRIPTION
**Pull request by kgryte**
- Return an empty data structure, not `null`.
- Handle non-numerics consistently. Return `NaN`.
- Move typed-array support to separate file.

### CODE REVIEW

**Comment by kgryte** [comment]
Module should be ready for review.

**Comment by Planeshifter** [comment]
Corrected a single copy-paste error I must have introduced earlier; code looks well to me and trying out the function with various inputs did not return anything unexpected. Publish?

**Comment by kgryte** [comment]
@Planeshifter Minor changes made, but probably worth taking another quick look to make sure no new typos, etc.

**Comment by Planeshifter** [comment]
LGTM.

**Comment by kgryte** [comment]
Thanks!

**Pull request merged**
